exports.ADMIN_ROOMS_REQUEST = 'ADMIN_ROOMS_REQUEST'
exports.ADMIN_ROOMS_SUCCESS = 'ADMIN_ROOMS_SUCCESS'
exports.ADMIN_ROOMS_FAIL = 'ADMIN_ROOMS_FAIL'

exports.ALL_ROOMS_REQUEST = 'ALL_ROOMS_REQUEST'
exports.ALL_ROOMS_SUCCESS = 'ALL_ROOMS_SUCCESS'
exports.ALL_ROOMS_FAIL = 'ALL_ROOMS_FAIL'

exports.NEW_ROOM_REQUEST = 'NEW_ROOM_REQUEST'
exports.NEW_ROOM_SUCCESS = 'NEW_ROOM_SUCCESS'
exports.NEW_ROOM_RESET = 'NEW_ROOM_RESET'
exports.NEW_ROOM_FAIL = 'NEW_ROOM_FAIL'

exports.DELETE_ROOM_REQUEST = 'DELETE_ROOM_REQUEST'
exports.DELETE_ROOM_SUCCESS = 'DELETE_ROOM_SUCCESS'
exports.DELETE_ROOM_RESET = 'DELETE_ROOM_RESET'
exports.DELETE_ROOM_FAIL = 'DELETE_ROOM_FAIL'

exports.UPDATE_ROOM_REQUEST = 'UPDATE_ROOM_REQUEST'
exports.UPDATE_ROOM_SUCCESS = 'UPDATE_ROOM_SUCCESS'
exports.UPDATE_ROOM_RESET = 'UPDATE_ROOM_RESET'
exports.UPDATE_ROOM_FAIL = 'UPDATE_ROOM_FAIL'

exports.ROOM_DETAILS_REQUEST = 'ROOM_DETAILS_REQUEST'
exports.ROOM_DETAILS_SUCCESS = 'ROOM_DETAILS_SUCCESS'
exports.ROOM_DETAILS_FAIL = 'ROOM_DETAILS_FAIL'

exports.NEW_REVIEW_REQUEST = 'NEW_REVIEW_REQUEST'
exports.NEW_REVIEW_SUCCESS = 'NEW_REVIEW_SUCCESS'
exports.NEW_REVIEW_RESET = 'NEW_REVIEW_RESET'
exports.NEW_REVIEW_FAIL = 'NEW_REVIEW_FAIL'

exports.GET_REVIEWS_REQUEST = 'GET_REVIEWS_REQUEST'
exports.GET_REVIEWS_SUCCESS = 'GET_REVIEWS_SUCCESS'
exports.GET_REVIEWS_FAIL = 'GET_REVIEWS_FAIL'

exports.DELETE_REVIEW_REQUEST = 'DELETE_REVIEW_REQUEST'
exports.DELETE_REVIEW_SUCCESS = 'DELETE_REVIEW_SUCCESS'
exports.DELETE_REVIEW_RESET = 'DELETE_REVIEW_RESET'
exports.DELETE_REVIEW_FAIL = 'DELETE_REVIEW_FAIL'

exports.CLEAR_ERRORS = 'CLEAR_ERRORS'